### ISSUE TITLE
Things to update

### ISSUE THREAD

**Issue by anoadragon453** [beardog108/firefox-privacy-addons#9]
* Remove Ghostery. They were selling private user data.
* Random Agent Spoofer will stop working in FF 57
* No Resource:// URI Leak is no longer necessary in FF 57
* Self-Destructing Cookies will stop working in FF 57

**Comment by beardog108** [comment]
We should replace self-destructing cookies with Cookie Autodelete

**Comment by anoadragon453** [comment]
Looks good. know if it erases cache / super cookies as well?

**Comment by beardog108** [comment]
Just cookies, i don't think it even erases localstorage. Its the best alternative currently to SDC.

**Comment by anoadragon453** [comment]
Dang, alright.

**Comment by beardog108** [comment]
done

**Comment by anoadragon453** [comment]
Cool, nice work.
